name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      FORCE_COLOR: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - name: Ruff check
        run: uv run ruff check --output-format=github

      - name: Ruff format
        run: uv run ruff format --check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Pytest
        run: uv run pytest
